title: Introduction to React
tagline: Take your first steps in modern frontend development
description: Learn React
template:
  name: intro-react
  repo: react-template
  description: 'A robot powered training repository :robot:'
before:
  - type: createIssue
    title: Welcome to React
    body: 00-setup.md
steps:
  - title: Clone the Repo
    description: "Welcome to React! Let's get started with our project."
    event: push
    actions:
      - type: respond
        with: 01-components.md
        issue: Welcome to React
