title: Introduction to React
tagline: Take your first steps in modern frontend development
description: In this course, you will learn the basics of React.js through building a gradebook web application to manage assignments, students, and grades.
template:
  name: intro-react
  repo: react-template
  description: 'A robot powered training repository :robot:'
before:
  - type: createIssue
    title: Welcome to React
    body: 00-setup.md
  - type: updateBranchProtection

steps:
  - title: Open a Pull Request
    description: Welcome to React! Let's get started with our project.
    event: pull_request.opened
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: gate
        left: '%payload.pull_request.title%'
        right: Changes
        operator: ===
        else:
          - type: respond
            with: Make sure the title of your PR is "Changes"
            issue: Welcome to React
      - type: respond
        with: 01-congrats.md
        issue: Changes
      - type: respond
        with: 01-components.md
        issue: Changes
      - type: createPullRequestComment
        body: header-component-activity.md
        file: src/App.jsx
        position: 85
        pullRequest: '%actions.metaPR2.data.number%'
  - title: Add a Header Component
    description: Give your app a title by adding a header component
    event: push
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: gate
        left: '%payload.ref%'
        operator: ===
        right: refs/heads/changes
      - type: getPullRequest
        pullRequest: Changes
        action_id: metaPR2
      - type: respond
        with: 02-props.md
        issue: Changes
      - type: createPullRequestComment
        body: import-child-component-activity.md
        file: src/App.jsx
        position: 3
        pullRequest: '%actions.metaPR2.data.number%'
  - title: Import a Child Component
    description: Give your app a title by adding a header component
    event: push
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: gate
        left: '%payload.ref%'
        operator: ===
        right: refs/heads/changes
      - type: getPullRequest
        pullRequest: Changes
        action_id: metaPR2
      - type: createPullRequestComment
        body: uncomment-assignments-activity.md
        file: src/App.jsx
        position: 46
        pullRequest: '%actions.metaPR2.data.number%'
  - title: Uncomment Assignments Functionality
    description: Give your app a title by adding a header component
    event: push
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: gate
        left: '%payload.ref%'
        operator: ===
        right: refs/heads/changes
      - type: getPullRequest
        pullRequest: Changes
        action_id: metaPR2
      - type: createPullRequestComment
        body: replace-title-activity.md
        file: src/List.jsx
        position: 5
        pullRequest: '%actions.metaPR2.data.number%'
  - title: State
    description: Learn how to deal with dynamic data
    event: push
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: gate
        left: '%payload.ref%'
        operator: ===
        right: refs/heads/changes
      - type: getPullRequest
        pullRequest: Changes
        action_id: metaPR2
      - type: getFileContents
        action_id: fileContents
        filename: 'src/App.jsx'
      - type: gate
        left: '/^\s*if\s*\(\s*this.state.buttonClicked\s*===\s*"assignments"\)\s*{\s*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*\n.*}\s*\n/gm'     
        operator: test
        right: '%actions.fileContents%'
        else:
          - type: respond
            with: bad-uncomment.md
            issue: Changes
      - type: respond
        with: 03-state.md
        issue: Changes
      - type: createPullRequestComment
        body: add-state-variable-activity.md
        file: src/App.jsx
        position: 12
        pullRequest: '%actions.metaPR2.data.number%'
      - type: createPullRequestComment
        body: explaining-this-state-activity.md
        file: src/App.jsx
        position: 32
        pullRequest: '%actions.metaPR2.data.number%'
      - type: createPullRequestComment
        body: create-addstudent-activity.md
        file: src/App.jsx
        position: 38
        pullRequest: '%actions.metaPR2.data.number%'
      - type: createPullRequestComment
        body: bind-function-activity.md
        file: src/App.jsx
        position: 20
        pullRequest: '%actions.metaPR2.data.number%'
  - title: Callback Functions
    description: Learn how to pass data back to parent components
    event: push
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: gate
        left: '%payload.ref%'
        operator: ===
        right: refs/heads/changes
      - type: getPullRequest
        pullRequest: Changes
        action_id: metaPR2
      - type: getFileContents
        action_id: fileContents
        filename: 'src/App.jsx'
      - type: gate
        left: '/^\s*this\.addStudent\s*=\s*this\.addStudent\.bind\s*\(\s*this\s*\)\s*;\s*\n/gm'
        operator: test
        right: '%actions.fileContents%'
        else:
          - type: respond
            with: bad-uncomment.md
            issue: Changes
      - type: getPullRequest
        pullRequest: Changes
        action_id: metaPR2
      - type: gate
        left: '/^\s*addStudent\s*\(\s*studentName\s*\)\s*/gm'     
        operator: test
        right: '%actions.fileContents%'
        else:
          - type: respond
            with: bad-function.md
            issue: Changes
      - type: respond
        with: 04-callbackfunctions.md
        issue: Changes
      - type: createPullRequestComment
        body: passing-functions-activity.md
        file: src/App.jsx
        position: 52
        pullRequest: '%actions.metaPR2.data.number%'
      - type: respond
        with: callback-example.md
        issue: Changes
      - type: createPullRequestComment
        body: change-props-students-activity.md
        file: src/App.jsx
        position: 68
        pullRequest: '%actions.metaPR2.data.number%'
      - type: createPullRequestComment
        body: uncomment-grades-activity.md
        file: src/App.jsx
        position: 78
        pullRequest: '%actions.metaPR2.data.number%'
  - title: Get Your Pull Request Approved
    event: push
    description: Let's confirm you made the right changes
    actions:
      - type: gate
        left: '%payload.ref%'
        operator: ===
        right: refs/heads/changes
      - type: createReview
        event: APPROVE
        body: approve.md
        pullRequest: Changes
  - title: Merge your Pull Request
    event: pull_request.closed
    description: Congrats on finishing the course!
    actions:
      - type: respond
        with: 05-congrats.md
        issue: Changes
    
