title: Introduction to React
tagline: Take your first steps in modern frontend development
description: Learn React
template:
  name: intro-react
  repo: react-template
  description: 'A robot powered training repository :robot:'
before:
  - type: createIssue
    title: Welcome to React
    body: 00-setup.md
    comments:
      - test.md

steps:
  - title: Setup and Components
    description: Welcome to React! Let's get started with our project.
    event: push
    actions:
      - type: gate
        left: '%payload.ref%'
        right: refs/heads/changes
        operator: ===
      - type: createPullRequest
        title: Title
        body: 01-components.md
        head: changes
        action_id: metaPR
      - type: octokit
        method: pullRequests.createComment
        owner: '%actions.metaPR.data.head.repo.owner.login%'
        repo: '%actions.metaPR.data.head.repo.name%'
        number: '%actions.metaPR.data.number%'
        commit_id: '%actions.metaPR.data.head.sha%'
        path: src/App.jsx
        body: add-component.md
        position: 15
  - title: Props
    actions:
      - type: gate
        left: '%payload.ref%'
        operator: ===
        right: refs/heads/changes
      - type: respond
        with: 02-props.md
        issue: Welcome to React
    description: Learn how to pass data to child components
    event: push
  - title: State
    actions:
      - type: gate
        left: '%payload.ref%'
        operator: ===
        right: refs/heads/changes
      - type: respond
        with: 03-state.md
        issue: Welcome to React
    description: Learn how to deal with dynamic data
    event: push
  - title: Callback Functions
    actions:
      - type: gate
        left: '%payload.ref%'
        operator: ===
        right: refs/heads/changes
      - type: respond
        with: 04-callbackfunctions.md
        issue: Welcome to React
    description: Learn how to pass data back to parent components
    event: push
